language: php
sudo: required
dist: trusty
php:
  - '7.1'
  - '7.2'

env:
  - NODE_RELEASE=10.x

before_script:
  - cp .env.travis .env
  - sudo rm -rf ~/.nvm
  - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
  - sudo apt-get install -y nodejs
  - mysql -u root -ppoowf -e 'create database invoiceneko_test;'
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan migrate
  - php artisan key:generate
  - npm i -g npm
  - npm install
  - npm run prod

script:
  - vendor/bin/phpunit
  - php artisan dusk

addons:
  chrome: stable
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client

before_install:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('poowf') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -ppoowf
  - sudo service mysql restart
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor